//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceSkill
    {
        public int ResourceSkillID { get; set; }
        public int SkillID { get; set; }
        public int ResourceID { get; set; }
        public int SkillValue { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
