//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.ResourceSkills = new HashSet<ResourceSkill>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ResourceId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal ProductivityIndex { get; set; }
    
        public virtual ICollection<ResourceSkill> ResourceSkills { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
